[package]
name = "ashiojin_extensions"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true, features = ["3d"] }
rand = { workspace = true }
rand_chacha = { workspace = true }
gltf = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }


# ---
# Workaround : see https://github.com/bevyengine/bevy/issues/10425
[dependencies.blake3]
version = "1.8"
features = ["pure"]
# ---
