[package]
name = "cc"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true, features = ["3d", "debug"] }
avian3d = { workspace = true }
thiserror = { workspace = true }
# --- from workspace ---

ashiojin_extensions = { path = "../../ashiojin_extensions" }

# ----------------------
serde = { version = "1", features = ["derive"] }
serde_json = "1"


# WORKAROUND
[dependencies.blake3]
version = "1.8"
features = ["pure"]
# WORKAROUND
