use bevy::{
    asset::RenderAssetUsages,
    math::{Vec3, primitives::Primitive3d},
    mesh::{Indices, Mesh, MeshBuilder, Meshable, MeshVertexAttribute, PrimitiveTopology},
    render::render_resource::VertexFormat,
};

pub const ATTRIBUTE_TIME: MeshVertexAttribute = MeshVertexAttribute::new(
    "Vertex_Time",
    1092837, // arbitrary unique ID for custom attribute
    VertexFormat::Float32,
);

/// A trail mesh generated by interpolating between a previous line and a current line over time.
#[derive(Copy, Clone, Debug)]
pub struct Trail {
    pub prev_root: Vec3,
    pub prev_tip: Vec3,
    pub curr_root: Vec3,
    pub curr_tip: Vec3,
    pub prev_time: f32,
    pub curr_time: f32,
    pub resolution: u32,
}

impl Primitive3d for Trail {}

impl Trail {
    #[inline]
    pub fn new(
        prev_root: Vec3,
        prev_tip: Vec3,
        curr_root: Vec3,
        curr_tip: Vec3,
        prev_time: f32,
        curr_time: f32,
    ) -> Self {
        Self {
            prev_root,
            prev_tip,
            curr_root,
            curr_tip,
            prev_time,
            curr_time,
            resolution: 32,
        }
    }

    pub fn with_resolution(mut self, resolution: u32) -> Self {
        assert!(resolution > 0, "resolution must be greater than 0");
        self.resolution = resolution;
        self
    }
}

impl Meshable for Trail {
    type Output = TrailMeshBuilder;

    fn mesh(&self) -> Self::Output {
        TrailMeshBuilder {
            prev_root: self.prev_root,
            prev_tip: self.prev_tip,
            curr_root: self.curr_root,
            curr_tip: self.curr_tip,
            prev_time: self.prev_time,
            curr_time: self.curr_time,
            resolution: self.resolution,
        }
    }
}

pub struct TrailMeshBuilder {
    pub prev_root: Vec3,
    pub prev_tip: Vec3,
    pub curr_root: Vec3,
    pub curr_tip: Vec3,
    pub prev_time: f32,
    pub curr_time: f32,
    pub resolution: u32,
}

impl MeshBuilder for TrailMeshBuilder {
    fn build(&self) -> Mesh {
        let mut vertices = Vec::new();
        let mut normals = Vec::new();
        let mut uvs = Vec::new();
        let mut times = Vec::new();
        let mut indices = Vec::new();

        let resolution_f = self.resolution as f32;

        for i in 0..=self.resolution {
            let t = i as f32 / resolution_f;

            // Interpolate root and tip using lerp.
            let root = self.prev_root.lerp(self.curr_root, t);
            let tip = self.prev_tip.lerp(self.curr_tip, t);

            // Interpolate time linearly
            let time = self.prev_time + t * (self.curr_time - self.prev_time);

            // Calculate directions for normal computation
            let dir = (tip - root).normalize_or_zero();

            // Movement direction:
            let move_dir = if t < 0.99 {
                let next_root = self.prev_root.lerp(self.curr_root, t + 0.01);
                (next_root - root).normalize_or_zero()
            } else {
                let prev_root = self.prev_root.lerp(self.curr_root, t - 0.01);
                (root - prev_root).normalize_or_zero()
            };

            // Normal is the cross product of the movement direction and the line direction.
            let normal = move_dir.cross(dir).normalize_or_zero();

            // We generate two vertices: one at root, one at tip
            vertices.push(root);
            vertices.push(tip);

            // Both vertices at this slice have the same normal (perpendicular to the ribbon surface)
            normals.push(normal);
            normals.push(normal);

            // UVs: U goes from 0 to 1 across steps, V goes from 0 to 1 (root is 0.0, tip is 1.0)
            uvs.push([t, 0.0]);
            uvs.push([t, 1.0]);

            // Both vertices get the interpolated time
            times.push(time);
            times.push(time);
        }

        // Generate indices for a triangle strip (represented as a TriangleList for simplicity)
        for i in 0..self.resolution {
            let base = i * 2;
            let next = (i + 1) * 2;

            // Face 1: base (root), next (root), base + 1 (tip)
            indices.push(base);
            indices.push(next);
            indices.push(base + 1);

            // Face 2: base + 1 (tip), next (root), next + 1 (tip)
            indices.push(base + 1);
            indices.push(next);
            indices.push(next + 1);
        }

        // We make it double-sided to be visible from any angle.
        let vertex_count = vertices.len();
        let index_offset = vertex_count as u32;

        let mut other_vertices = vertices.clone();
        let other_uvs = uvs.clone();
        let mut other_normals = Vec::with_capacity(vertex_count);
        let other_times = times.clone();

        for n in &normals {
            other_normals.push(-*n);
        }

        vertices.append(&mut other_vertices);
        uvs.extend(other_uvs);
        normals.append(&mut other_normals);
        times.extend(other_times);

        // Indices for the second side (Inner) with reversed winding
        for i in 0..self.resolution {
            let base = i * 2 + index_offset;
            let next = (i + 1) * 2 + index_offset;

            indices.push(base);
            indices.push(base + 1);
            indices.push(next);

            indices.push(base + 1);
            indices.push(next + 1);
            indices.push(next);
        }

        Mesh::new(
            PrimitiveTopology::TriangleList,
            RenderAssetUsages::default(),
        )
        .with_inserted_indices(Indices::U32(indices))
        .with_inserted_attribute(Mesh::ATTRIBUTE_POSITION, vertices)
        .with_inserted_attribute(Mesh::ATTRIBUTE_NORMAL, normals)
        .with_inserted_attribute(Mesh::ATTRIBUTE_UV_0, uvs)
        .with_inserted_attribute(ATTRIBUTE_TIME, times)
    }
}

/// The interpolation mode for the trail mesh.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Hash)]
pub enum TrailInterpolationMode {
    /// Use Catmull-Rom spline interpolation for all segments.
    #[default]
    CatmullRom,
    /// Use Catmull-Rom spline interpolation for older segments, but linear
    /// interpolation (lerp) for the latest segment leading up to the active emitter.
    LinearLastSegment,
}

/// A point along the historical path of a trail emitter.
#[derive(Debug, Clone)]
pub struct SplineTrailPoint {
    pub root: Vec3,
    pub tip: Vec3,
    pub time: f32,
    /// When `true`, the trail is cut *before* this point: no ribbon is drawn
    /// connecting the previous point to this one. This lets a single history
    /// hold several temporally-separated bursts without bridging the gaps
    /// between them into one continuous trail.
    pub break_before: bool,
}

/// A spline-interpolated trail mesh builder that generates a single mesh from a history of points.
pub struct SplineTrail {
    pub points: Vec<SplineTrailPoint>,
    pub subdivisions: u32,
}

impl SplineTrail {
    pub fn new(points: Vec<SplineTrailPoint>, subdivisions: u32) -> Self {
        Self { points, subdivisions }
    }

    /// Build a single Bevy Mesh using the specified interpolation mode.
    ///
    /// Returns `None` when the history holds no drawable ribbon, i.e. no run of
    /// consecutive (unbroken) points is at least two points long. Callers must
    /// not substitute an empty `Mesh`: bevy's `MeshAllocator` skips allocating
    /// for a zero-vertex mesh but still tries to copy its vertex data, which
    /// logs "Use-after-free: attempted to copy element data for an unallocated
    /// key".
    pub fn build_mesh(&self, mode: TrailInterpolationMode) -> Option<Mesh> {
        // Split the history into contiguous runs, cutting *before* any point
        // flagged `break_before`. Each run becomes an independent ribbon, so
        // temporally separated bursts are never bridged into one long trail.
        let mut runs: Vec<&[SplineTrailPoint]> = Vec::new();
        if !self.points.is_empty() {
            let mut start = 0;
            for i in 1..self.points.len() {
                if self.points[i].break_before {
                    runs.push(&self.points[start..i]);
                    start = i;
                }
            }
            runs.push(&self.points[start..]);
        }
        // Only runs with at least two points can form a ribbon.
        runs.retain(|r| r.len() >= 2);

        if runs.is_empty() {
            return None;
        }

        struct Slice {
            root: Vec3,
            tip: Vec3,
            time: f32,
            u: f32,
        }

        // Global parameterisation so UV.x still runs 0..1 across the whole
        // history (matching the single-run behaviour exactly when there are
        // no breaks). Counted in point-to-point segments across all runs.
        let total_point_segments: usize = runs.iter().map(|r| r.len() - 1).sum();
        let total_subdiv_segments_f =
            (total_point_segments * self.subdivisions as usize) as f32;

        let mut slices: Vec<Slice> = Vec::new();
        // (start, end) slice-index range per run, so triangles never span runs.
        let mut run_ranges: Vec<(usize, usize)> = Vec::new();

        let mut seg_offset = 0usize; // point-segments consumed by earlier runs
        let last_run_idx = runs.len() - 1;

        for (run_idx, run) in runs.iter().enumerate() {
            let run_start_slice = slices.len();
            let n = run.len();

            for i in 0..n - 1 {
                let p0 = if i > 0 { &run[i - 1] } else { &run[0] };
                let p1 = &run[i];
                let p2 = &run[i + 1];
                let p3 = if i + 2 < n { &run[i + 2] } else { &run[n - 1] };

                let is_last_segment = i == n - 2;
                // Linear-last-segment applies only to the actively growing
                // (last) run's final segment.
                let use_linear = is_last_segment
                    && run_idx == last_run_idx
                    && mode == TrailInterpolationMode::LinearLastSegment;

                let max_s = if is_last_segment { self.subdivisions } else { self.subdivisions - 1 };

                for s in 0..=max_s {
                    let u = s as f32 / self.subdivisions as f32;
                    let global_idx = (seg_offset + i) * self.subdivisions as usize + s as usize;
                    let global_u = if total_subdiv_segments_f > 0.0 {
                        global_idx as f32 / total_subdiv_segments_f
                    } else {
                        0.0
                    };

                    let (root, tip, time) = if use_linear {
                        (
                            p1.root.lerp(p2.root, u),
                            p1.tip.lerp(p2.tip, u),
                            p1.time + u * (p2.time - p1.time),
                        )
                    } else {
                        (
                            catmull_rom(p0.root, p1.root, p2.root, p3.root, u),
                            catmull_rom(p0.tip, p1.tip, p2.tip, p3.tip, u),
                            p1.time + u * (p2.time - p1.time),
                        )
                    };

                    slices.push(Slice { root, tip, time, u: global_u });
                }
            }

            run_ranges.push((run_start_slice, slices.len()));
            seg_offset += n - 1;
        }

        let mut vertices = Vec::with_capacity(slices.len() * 2);
        let mut normals_attr = Vec::with_capacity(slices.len() * 2);
        let mut uvs = Vec::with_capacity(slices.len() * 2);
        let mut times = Vec::with_capacity(slices.len() * 2);
        let mut indices: Vec<u32> = Vec::new();

        let mut last_valid_normal = Vec3::Y;
        let mut base_vertex = 0u32; // running front-side vertex offset per run

        for &(start, end) in &run_ranges {
            for k in start..end {
                let slice = &slices[k];
                let dir = (slice.tip - slice.root).normalize_or_zero();

                // Movement direction stays within the run so boundaries don't
                // pull the normal toward a neighbouring, disconnected run.
                let move_dir = if k + 1 < end {
                    (slices[k + 1].root - slice.root).normalize_or_zero()
                } else if k > start {
                    (slice.root - slices[k - 1].root).normalize_or_zero()
                } else {
                    Vec3::ZERO
                };

                let mut normal = move_dir.cross(dir).normalize_or_zero();
                if normal == Vec3::ZERO {
                    normal = last_valid_normal;
                } else {
                    last_valid_normal = normal;
                }

                vertices.push(slice.root);
                vertices.push(slice.tip);

                normals_attr.push(normal);
                normals_attr.push(normal);

                uvs.push([slice.u, 0.0]);
                uvs.push([slice.u, 1.0]);

                times.push(slice.time);
                times.push(slice.time);
            }

            let run_slices = (end - start) as u32;
            for i in 0..run_slices.saturating_sub(1) {
                let base = base_vertex + i * 2;
                let next = base_vertex + (i + 1) * 2;

                // Face 1: base (root), next (root), base + 1 (tip)
                indices.push(base);
                indices.push(next);
                indices.push(base + 1);

                // Face 2: base + 1 (tip), next (root), next + 1 (tip)
                indices.push(base + 1);
                indices.push(next);
                indices.push(next + 1);
            }

            base_vertex += run_slices * 2;
        }

        let vertex_count = vertices.len();
        let index_offset = vertex_count as u32;

        let mut other_vertices = vertices.clone();
        let other_uvs = uvs.clone();
        let mut other_normals = Vec::with_capacity(vertex_count);
        let other_times = times.clone();

        for n in &normals_attr {
            other_normals.push(-*n);
        }

        vertices.append(&mut other_vertices);
        uvs.extend(other_uvs);
        normals_attr.append(&mut other_normals);
        times.extend(other_times);

        // Indices for the second side (Inner) with reversed winding, again
        // connecting only within each run.
        let mut base_vertex = 0u32;
        for &(start, end) in &run_ranges {
            let run_slices = (end - start) as u32;
            for i in 0..run_slices.saturating_sub(1) {
                let base = index_offset + base_vertex + i * 2;
                let next = index_offset + base_vertex + (i + 1) * 2;

                indices.push(base);
                indices.push(base + 1);
                indices.push(next);

                indices.push(base + 1);
                indices.push(next + 1);
                indices.push(next);
            }
            base_vertex += run_slices * 2;
        }

        Some(
            Mesh::new(
                PrimitiveTopology::TriangleList,
                RenderAssetUsages::default(),
            )
            .with_inserted_indices(Indices::U32(indices))
            .with_inserted_attribute(Mesh::ATTRIBUTE_POSITION, vertices)
            .with_inserted_attribute(Mesh::ATTRIBUTE_NORMAL, normals_attr)
            .with_inserted_attribute(Mesh::ATTRIBUTE_UV_0, uvs)
            .with_inserted_attribute(ATTRIBUTE_TIME, times),
        )
    }
}

/// Helper function to interpolate using Catmull-Rom spline
pub fn catmull_rom(p0: Vec3, p1: Vec3, p2: Vec3, p3: Vec3, t: f32) -> Vec3 {
    let t2 = t * t;
    let t3 = t2 * t;
    0.5 * (
        (2.0 * p1) +
        (-p0 + p2) * t +
        (2.0 * p0 - 5.0 * p1 + 4.0 * p2 - p3) * t2 +
        (-p0 + 3.0 * p1 - 3.0 * p2 + p3) * t3
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_trail_mesh() {
        let trail = Trail::new(
            Vec3::new(1.0, 0.0, 0.0),
            Vec3::new(1.0, 1.0, 0.0),
            Vec3::new(0.0, 1.0, 0.0),
            Vec3::new(0.0, 2.0, 0.0),
            0.0,
            1.0,
        ).with_resolution(10);
        
        let mesh = trail.mesh().build();
        
        // Resolution 10 means 11 steps.
        // Each step has 2 vertices.
        // Total vertices per side: 11 * 2 = 22.
        // Double-sided: 22 * 2 = 44.
        assert_eq!(mesh.count_vertices(), 44);
        
        // 10 segments.
        // Each segment has 2 triangles per side.
        // Each triangle has 3 indices.
        // Indices per side: 10 * 2 * 3 = 60.
        // Double-sided: 60 * 2 = 120.
        assert_eq!(mesh.indices().unwrap().len(), 120);

        // Verify that custom time attribute exists
        assert!(mesh.attribute(ATTRIBUTE_TIME.id).is_some());
    }

    #[test]
    fn test_spline_trail_mesh() {
        let points = vec![
            SplineTrailPoint {
                root: Vec3::new(0.0, 0.0, 0.0),
                tip: Vec3::new(0.0, 1.0, 0.0),
                time: 0.0,
                break_before: false,
            },
            SplineTrailPoint {
                root: Vec3::new(1.0, 0.0, 0.0),
                tip: Vec3::new(1.0, 1.2, 0.0),
                time: 0.1,
                break_before: false,
            },
            SplineTrailPoint {
                root: Vec3::new(2.0, 0.0, 1.0),
                tip: Vec3::new(2.0, 1.5, 1.0),
                time: 0.2,
                break_before: false,
            },
        ];

        let spline = SplineTrail::new(points, 4);
        
        let mesh_cr = spline.build_mesh(TrailInterpolationMode::CatmullRom).unwrap();
        let mesh_linear = spline
            .build_mesh(TrailInterpolationMode::LinearLastSegment)
            .unwrap();

        // 3 points = 2 segments.
        // 2 segments * 4 subdivisions = 8 segments total.
        // 8 segments means 9 slices of vertices.
        // Each slice has 2 vertices = 18 vertices per side.
        // Double-sided = 36 vertices total.
        assert_eq!(mesh_cr.count_vertices(), 36);
        assert_eq!(mesh_linear.count_vertices(), 36);

        // 8 segments * 2 triangles per side * 3 indices * 2 sides = 96 indices.
        assert_eq!(mesh_cr.indices().unwrap().len(), 96);
        assert_eq!(mesh_linear.indices().unwrap().len(), 96);
    }

    #[test]
    fn test_spline_trail_break_disconnects_runs() {
        // Two temporally-separated bursts sharing one history:
        // points 0..=1 are burst A (near x=0..1), points 2..=3 are burst B (near x=5..6).
        // `break_before` on point 2 must prevent a connecting ribbon across the gap.
        let subdivisions = 4;
        let points = vec![
            SplineTrailPoint {
                root: Vec3::new(0.0, 0.0, 0.0),
                tip: Vec3::new(0.0, 1.0, 0.0),
                time: 0.0,
                break_before: false,
            },
            SplineTrailPoint {
                root: Vec3::new(1.0, 0.0, 0.0),
                tip: Vec3::new(1.0, 1.0, 0.0),
                time: 0.1,
                break_before: false,
            },
            SplineTrailPoint {
                root: Vec3::new(5.0, 0.0, 0.0),
                tip: Vec3::new(5.0, 1.0, 0.0),
                time: 2.0,
                break_before: true,
            },
            SplineTrailPoint {
                root: Vec3::new(6.0, 0.0, 0.0),
                tip: Vec3::new(6.0, 1.0, 0.0),
                time: 2.1,
                break_before: false,
            },
        ];

        let spline = SplineTrail::new(points, subdivisions);
        let mesh = spline.build_mesh(TrailInterpolationMode::CatmullRom).unwrap();

        // Two independent runs of 2 points each. Each run = 1 * subdivisions = 4 quads
        // spanning 5 slices → 10 vertices/side. Double-sided → 40 vertices, 96 indices.
        // A single connected run of 4 points would instead have 3 * subdivisions = 12
        // quads (13 slices), i.e. the extra bridging segment we must NOT generate.
        assert_eq!(mesh.count_vertices(), 40);
        assert_eq!(mesh.indices().unwrap().len(), 96);

        // Behavioral check: nothing should be drawn in the gap between the two bursts.
        // A bridging Catmull-Rom segment from x=1 to x=5 would place vertices around x=3.
        let positions = mesh
            .attribute(Mesh::ATTRIBUTE_POSITION)
            .and_then(|a| a.as_float3())
            .unwrap();
        for p in positions {
            assert!(
                p[0] <= 1.5 || p[0] >= 4.5,
                "vertex at x={} lies in the gap between bursts; runs were bridged",
                p[0]
            );
        }
    }

    #[test]
    fn test_spline_trail_without_any_ribbon_yields_no_mesh() {
        // A break can leave *every* run a single point: the previous burst has
        // decayed down to one surviving point and the new burst has just pushed
        // its first (break-flagged) point. There is no ribbon to draw at all.
        //
        // Such a history must not produce a Mesh: a zero-vertex mesh handed to
        // `Assets<Mesh>` makes bevy's MeshAllocator free the old GPU allocation
        // and then still attempt the vertex copy, logging
        // "Use-after-free: attempted to copy element data for an unallocated key".
        let points = vec![
            SplineTrailPoint {
                root: Vec3::new(0.0, 0.0, 0.0),
                tip: Vec3::new(0.0, 1.0, 0.0),
                time: 0.0,
                break_before: false,
            },
            SplineTrailPoint {
                root: Vec3::new(5.0, 0.0, 0.0),
                tip: Vec3::new(5.0, 1.0, 0.0),
                time: 2.0,
                break_before: true,
            },
        ];

        let spline = SplineTrail::new(points, 4);

        assert!(
            spline.build_mesh(TrailInterpolationMode::CatmullRom).is_none(),
            "no run has two points, so there is nothing to draw"
        );
    }

    #[test]
    fn test_spline_trail_lone_point_run_is_dropped() {
        // A break can isolate a single point (e.g. after old points are pruned).
        // That one-point run cannot form a ribbon and must be dropped, leaving
        // only the valid two-point run — without panicking or bridging.
        let subdivisions = 4;
        let points = vec![
            SplineTrailPoint {
                root: Vec3::new(0.0, 0.0, 0.0),
                tip: Vec3::new(0.0, 1.0, 0.0),
                time: 0.0,
                break_before: false,
            },
            SplineTrailPoint {
                root: Vec3::new(5.0, 0.0, 0.0),
                tip: Vec3::new(5.0, 1.0, 0.0),
                time: 2.0,
                break_before: true,
            },
            SplineTrailPoint {
                root: Vec3::new(6.0, 0.0, 0.0),
                tip: Vec3::new(6.0, 1.0, 0.0),
                time: 2.1,
                break_before: false,
            },
        ];

        let spline = SplineTrail::new(points, subdivisions);
        let mesh = spline.build_mesh(TrailInterpolationMode::CatmullRom).unwrap();

        // Only the [p1, p2] run survives: 1 * subdivisions = 4 quads, 5 slices,
        // 10 verts/side → 20 verts double-sided, 48 indices.
        assert_eq!(mesh.count_vertices(), 20);
        assert_eq!(mesh.indices().unwrap().len(), 48);
    }
}
