[package]
name = "previewer"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true, features = ["3d"] }
rand = { workspace = true }
rand_chacha = { workspace = true }
gltf = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

tokio = { version = "1", features = ["full"] }
axum = { version= "0.7", features = ["macros"] }
tower-http = { version = "0.5", features = ["cors"] }

ashiojin_extensions = { path = "../ashiojin_extensions" }

# clap = { version = "4.6" }
# indexmap = { version = "2.14" }
# bytemuck = { version = "1.24" }
# nonmax = { version = "0.5" }
# ---
# Workaround : see https://github.com/bevyengine/bevy/issues/10425
[dependencies.blake3]
version = "1.8"
features = ["pure"]
# ---
